routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'IndexController@index')->name('index');
Route::get('/about', 'IndexController@about')->name('about');
Route::get('/volunteers', 'IndexController@volunteers')->name('volunteers');
Route::get('/support', 'IndexController@support')->name('support');
Route::get('/thank-you', 'IndexController@thankYou')->name('thank-you');
Route::get('/ref/{ref}', 'IndexController@referral')->name('referral');
Route::get('/project/{project}', 'ProjectsController@view');

Auth::routes();

Route::post('/donate', 'DonationController@donate')->name('donate');
Route::post('/donate/upload-photo', 'DonationController@uploadPhoto');
Route::post('/register-volunteer', 'DonorController@registerVolunteer');

Route::prefix('/admin')
    ->middleware('auth')
    ->group(function () {
        Route::get('/', 'HomeController@index')->name('home');

        Route::resource('projects', 'Admin\\ProjectsController');
    });

app/Donor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

/**
 * App\Donor
 *
 * @property int $id
 * @property string|null $uuid
 * @property string $email
 * @property string $name
 * @property string|null $surname
 * @property int|null $referrer
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property string|null $phone
 * @property string|null $tg
 * @property string|null $vk
 * @property string|null $inst
 * @property string|null $fb
 * @property string|null $photo
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Donor newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Donor newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Donor query()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Donor whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Donor whereEmail($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Donor whereFb($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Donor whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Donor whereInst($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Donor whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Donor wherePhone($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Donor wherePhoto($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Donor whereReferrer($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Donor whereSurname($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Donor whereTg($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Donor whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Donor whereUuid($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Donor whereVk($value)
 * @mixin \Eloquent
 */
class Donor extends Model
{
    protected $guarded = ['id'];

    public function scopeVolunteers(Builder $query)
    {
        return $query->where('is_volunteer', '=', true);
    }

    public function getCollectedAttribute()
    {
        return $this->referrals()->sum('amount');
    }

    public function referrals()
    {
        return $this->hasMany(Donation::class, 'referrer');
    }

    public function donations()
    {
        return $this->hasMany(Donation::class, 'donor_id');
    }
}

resources/views/about.blade.php
@extends('layouts.main')

@section('title', 'Шиес | О фонде')

@section('content')
    <div class="page__row">
        <main class="page__main">
            <!-- titer--about-->
            <section class="titer titer--about">
                <div class="titer__inner inner">
                    <h1 class="titer__heading pageTitle">О фонде</h1>
                    <div class="titer__body">
                        <p>
                            <strong>SaveShies</strong> - сайт автономной некоммерческой организации “Шиес”, созданной в
                            ноябре 2019 года.
                        </p>
                        <p>
                            Мы занимаемся поддержкой активистов Шиеса, собираем деньги на штрафы, юридическую помощь и
                            другие нужды гражданского общества.
                        </p>
                        <p>
                            <strong>Наша стратегия</strong> заключается в публичном открытом и системном сборе средств
                            для поддержки
                            отдельных активистов и движения в целом. Мы уверены, что российское общество созрело для
                            солидарности и фандрайзинга гражданских инициатив. И когда власть применяет такой элемент
                            давления как большой штраф - задача граждан этот вопрос с повестки дня снять.
                        </p>
                        <p>
                            В истории России нечасто русские люди самоорганизовываются, но когда это происходит, то
                            поддержка самоорганизации это долг каждого, кто любит Россию, желает ей мира и процветания.
                        </p>
                        <p>
                            <strong>Наша миссия</strong> - помогать экологическим активистам и навсегда закрыть вопрос
                            мусорного полигона
                            в Шиесе.
                        </p>
                        <p>
                            Мы верим, что сообща наше общество способно противостоять небольшой и коррумпированной
                            группе сторонников строительства полигона. Россия - страна для россиян, а не для мусорной
                            мафии.
                        </p>
                    </div>
                </div>
            </section><!-- goals-->
            <section class="goals">
                <div class="goals__inner inner">
                    <h2 class="goals__heading blockTitle">Наши цели</h2>
                    <ul class="goals__list listReset">
                        <li class="goals__item">
                            <span class="goals__icon"><img src="/files/goals/new-system.svg" alt=""></span>
                            <span class="goals__title">Прекращение преследования активистов</span>
                        </li>
                        <li class="goals__item">
                            <span class="goals__icon"><img src="/files/goals/recult.svg" alt=""></span>
                            <span class="goals__title">Прекращение строительства свалки на Шиесе</span>
                        </li>
                        <li class="goals__item">
                            <span class="goals__icon"><img src="/files/goals/ban.svg" alt=""></span>
                            <span class="goals__title">Восстановление нанесенного природе ущерба </span>
                        </li>
                        <li class="goals__item">
                            <span class="goals__icon"><img src="/files/goals/new-system.svg" alt=""></span>
                            <span class="goals__title">Переход на новую систему обращения с отходами</span>
                        </li>
                        <li class="goals__item">
                            <span class="goals__icon"><img src="/files/goals/recult.svg" alt=""></span>
                            <span class="goals__title">Рекультивация действующих полигонов</span>
                        </li>
                        <li class="goals__item">
                            <span class="goals__icon"><img src="/files/goals/ban.svg" alt=""></span>
                            <span class="goals__title">Законодательный запрет ввоза отходов из других регионов</span>
                        </li>
                    </ul>
                </div>
            </section><!-- textBlock--ways-->
            <section class="textBlock">
                <div class="textBlock__inner inner">
                    <h2 class="textBlock__title blockTitle">Пути достижения</h2>
                    <div class="textBlock__body">
                        <p>Бессрочный протест или просто «Бессрочка» — это форма публичного обращения граждан к властям,
                            которые не желают слышать волю народа. Мирный протест, не нарушающий законодательства
                            страны.</p>
                        <ul>
                            <li>Информирование власти о существующих проблемах и предложение способов их решения.</li>
                            <li>Информирование граждан об общественных проблемах через беседы или привлечение СМИ.</li>
                            <li>Знакомства и общение с единомышленниками.</li>
                            <li>«Перевалочные базы» для Шиеса.</li>
                        </ul>
                    </div>
                </div>
            </section><!-- textBlock--info-->
            <section class="textBlock textBlock--info">
                <div class="textBlock__inner inner">
                    <h2 class="textBlock__title blockTitle">Реквизиты и учредительные документы</h2>
                    <div class="textBlock__body">
                        <p>Автономная некоммерческая организация помощи активистам «SaveШиес». ОГРН 1187700007472 от 25
                            апреля 2018 года, ИНН/КПП 7720423186 / 772001001. Юридический адрес 1111123, Москва, ул.
                            Плеханова, д 4 А, офис 43 В.</p>
                    </div>
                    <div class="textBlock__files">
                        <!-- files-->
                        <ul class="files listReset">
                            <li class="files__item">
                                <a class="files__file" href="#0">Свидетельство о внесении в единый государственный
                                    реестр юридических лиц</a>
                            </li>
                            <li class="files__item">
                                <a class="files__file" href="#0">Свидетельство о постановке на учет в налоговом органе
                                    (ИНН)</a>
                            </li>
                            <li class="files__item">
                                <a class="files__file" href="#0">Публичная оферта о заключении договора
                                    пожертвования</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </section>
        </main>
    </div>
@endsection

resources/views/referral-page.blade.php
@extends('layouts.main')

@section('title', 'SaveШиес')

@section('content')

<div class="page__row">
    <main class="page__main">
        <!-- referral-page-->
        <section class="referralPage">
            <div class="referralPage__inner inner">
                <h1 class="referralPage__heading pageTitle">Вас просит сделать пожертвование</h1>
                <div class="referralPage__volunteer">
                    <!-- volunteer-card-->
                    <section class="volunteerCard volunteerCard--full">
                        <div class="volunteerCard__image">
                            <img src="{{ url(Storage::url($donor->photo)) }}" alt="Волонтер благотворительного фонда SaveШиес undefined">
                        </div>
                        <div class="volunteerCard__cnt">
                            <h3 class="volunteerCard__name">{{ $donor->name }} {{ $donor->surname }}<span class="volunteerCard__tooltip" hidden>Вы перешли по ссылке от нашего волонтера. Мы не перечисляем процент волонтерам, но очень их благодарим за помощь</span>
                            </h3>
                            <div class="volunteerCard__state">
                                <div class="volunteerCard__label">Собрано</div>
                                <div class="volunteerCard__value">{{ number_format($donor->collected, 0, '.', ' ') }} ₽</div>
                            </div>
                            <div class="volunteerCard__state">
                                <div class="volunteerCard__label">Поддержали</div>
                                <div class="volunteerCard__value">{{ number_format($donor->referrals()->count(), 0, '.', ' ') }} чел</div>
                            </div>
                        </div>
                    </section>
                </div>
                <div class="referralPage__form">
                    <!-- form--donate-->
                    <form class="form form--donate" method="POST" action="{{ route('donate') }}">
                        @csrf
                        <fieldset class="form__item form__item--type">
                            <legend class="form__label">Вид пожертвования</legend>
                            <div class="form__row form__row--radio">
                                <label class="form__radio">
                                    <input type="radio" name="donate-type" value="monthly" required checked><span class="form__value">Ежемесячное</span>
                                </label>
                                <label class="form__radio">
                                    <input type="radio" name="donate-type" value="single" required><span class="form__value">Разовое</span>
                                </label>
                            </div>
                            <div class="form__tip">*Ежемесячное пожертвование раз в месяц списывается с банковской карты, Яндекс кошелька или Крипто кошелька. Вы в любой момент сможете отключить его.</div>
                        </fieldset>
                        <div class="form__row form__row--amount">
                            <label class="form__item"><span class="form__label">Ваш имейл</span>
                                <input class="form__field" type="email" name="email" required placeholder="Введите имейл" />
                            </label>
                            <fieldset class="form__item">
                                <legend class="form__label">Сумма пожертвования</legend>
                                <div class="form__amountWrp">
                                    <label class="form__amount form__amount--chbx">
                                        <input type="radio" name="amount-fix" value="1000"><span class="form__amountText">1000</span>
                                    </label>
                                    <label class="form__amount form__amount--chbx">
                                        <input type="radio" name="amount-fix" value="2000" checked><span class="form__amountText">2000</span>
                                    </label>
                                    <label class="form__amount form__amount--chbx">
                                        <input type="radio" name="amount-fix" value="3000"><span class="form__amountText">3000</span>
                                    </label>
                                    <label class="form__amount form__amount--input">
                                        <input class="form__field" type="text" name="amount" placeholder="Своя сумма" />
                                    </label>
                                </div>
                            </fieldset>
                        </div>
                        <div class="form__row">
                            <div class="form__label">Личные данные</div>
                            <div class="form__item">
                                <input class="form__field" type="text" name="name" required placeholder="Имя" />
                            </div>
                            <div class="form__item">
                                <input class="form__field" type="text" name="surname" required placeholder="Фамилия" />
                            </div>
                        </div>
                        <fieldset class="form__row form__row--payment">
                            <legend class="form__label">Выберите способ оплаты</legend>
                            <div class="form__paymentWrp">
                                <label class="form__payment form__payment--yandex">
                                    <input type="radio" name="payment" value="yandex" checked><span class="form__paymentText">Яндекс. деньги</span>
                                </label>
{{--                                <label class="form__payment form__payment--card">--}}
{{--                                    <input type="radio" name="payment" value="card"><span class="form__paymentText">Банковский перевод</span>--}}
{{--                                </label>--}}
{{--                                <label class="form__payment form__payment--bitcoin">--}}
{{--                                    <input type="radio" name="payment" value="bitcoin"><span class="form__paymentText">Биткойн перевод</span>--}}
{{--                                </label>--}}
                            </div>
                        </fieldset>
                        <div class="form__item form__item--volunteer visually-hidden">
                            <div class="form__label">Кто из волонтеров направил Вас?
                                <input class="form__volunteerSelect" type="hidden" name="referrer" value="{{ $donor->id }}" readonly />
                            </div>
                        </div>
                        <label class="form__item form__item--checkbox">
                            <input type="checkbox" name="offer-agree" required><span class="form__label">Соглашаюсь с <a href="#0" target="_blank">офертой</a></span>
                        </label>
                        <label class="form__item form__item--checkbox">
                            <input type="checkbox" name="offer-agree" required><span class="form__label">Соглашаюсь на <a href="#0" target="_blank">обработку персональных данных</a></span>
                        </label>
                        <input class="form__source" hidden type="text" name="source" value="Общий фонд">
                        <div class="form__actions">
                            <button class="button form__button" type="submit">Поддержать фонд</button>
                            <a class="form__link" href="#0" target="_blank">Управлять ежемесячным платежом</a>
                        </div>
                    </form>
                </div>
            </div>
        </section>
    </main>
</div>
@endsection

resources/views/thank-you.blade.php
@extends('layouts.main')

@section('title', 'Шиес | Главная')

@section('content')
    <div class="page__row">
        <main class="page__main">
            <div class="loadPhoto">
                <div class="loadPhoto__inner inner">
                    <h1 class="loadPhoto__heading pageTitle">Загрузите Ваше фото</h1>
                    <div class="loadPhoto__body">
                        <p>Ваше фото будет отображено на странице поддержавших наш фонд публично. Вы
                            можете перетащить фото на область со штриховкой или загрузить фото с
                            вконтакте</p>
                    </div>
                    <form class="loadPhoto__form" method="post" enctype="multipart/form-data" action="/donate/upload-photo">
                        @csrf
                        <div class="loadPhoto__imgZone">
                            <div class="loadPhoto__image">
                                <img src="/files/photo-placeholder.svg" alt="">
                            </div>
                            <div class="loadPhoto__name">Алексей Македонский</div>
                            <div class="loadPhoto__buttons">
                                <button disabled class="loadPhoto__uploadBtn loadPhoto__uploadBtn--vk"
                                        type="button">Загрузить с вк
                                </button>
                                <button class="loadPhoto__uploadBtn loadPhoto__uploadBtn--comp"
                                        type="button">Загрузить с компьютера
                                </button>
                            </div>
                            <input type="file" name="file" hidden>
                        </div>
                        <div class="loadPhoto__actions">
                            <button class="button loadPhoto__button" type="submit">Резместить фото
                            </button>
                            <a class="button loadPhoto__button" href="{{ url('volunteers') }}">Не хочу размещать фото</a>
                        </div>
                    </form>
                </div>
            </div>
        </main>
    </div>
@endsection

resources/views/volunteers.blade.php
@extends('layouts.main')

@section('title', 'Шиес | Волонтерская программа')

@section('content')
    <div class="page__row">
        <main class="page__main">
            <!-- titer--volunteers-->
            <section class="titer titer--volunteers">
                <div class="titer__inner inner">
                    <h1 class="titer__heading pageTitle">Волонтерская программа</h1>
                    <div class="titer__body">
                        <p>
                            Волонтерская программа, это дополнительный инструмент для фандрайзинга. Любой желающий,
                            будь-то
                            один человек, коллектив, СМИ или предприятие, может зарегистрироваться и принять в ней
                            участие.
                            После простой регистрации волонтер получает на почту уникальные реферальные ссылки для
                            размещения в соц. сетях или на сайтах. Для жертвователя всё выглядит как обычно, но
                            поступившие
                            со ссылкой деньги засчитываются, как привлеченные волонтером.
                        </p>
                        <p>
                            Наши волонтеры не получают за свою помощь никакого финансового вознаграждения, их заслуги и
                            помощь мы будем отмечать благодарностью, упоминанием в наших соц.сетях и участием в рейтинге
                            волонтеров.
                        </p>
                    </div>
                    <div class="titer__footer">
                        <a class="button titer__button" href="#0" data-modal=".modal--reg">Стать волонтером</a>
                    </div>
                </div>
            </section><!-- volunteers-->
            <section class="volunteers">
                <div class="volunteers__inner inner">
                    <h2 class="volunteers__heading blockTitle">Лучшие волонтеры</h2>
                    <ul class="volunteers__list listReset">
                        @foreach($volunteers_select as $volunteer)
                            <li class="volunteers__item">
                                <!-- volunteer-card-->
                                <section class="volunteerCard">
                                    <div class="volunteerCard__image">
                                        <img src="{{ url(Storage::url($volunteer->photo)) }}"
                                             alt="Волонтер благотворительного фонда SaveШиес {{ $volunteer->name }} {{ $volunteer->surname }}">
                                    </div>
                                    <div class="volunteerCard__cnt">
                                        <h3 class="volunteerCard__name">
                                            <a href="{{ url('/ref/'.$volunteer->uuid) }}">{{ $volunteer->name }} {{ $volunteer->surname }}</a>
                                        </h3>
                                        <div class="volunteerCard__text">Собрано - {{ number_format($volunteer->collected, 0, '.', ' ') }} ₽</div>
                                    </div>
                                </section>
                            </li>
                        @endforeach
                    </ul>
                </div>
            </section><!-- blackBlock--reg-->
            <section class="blackBlock blackBlock--reg">
                <div class="blackBlock__inner inner">
                    <h2 class="blackBlock__heading blockTitle">Чтобы оказаться в этом почетном топе волонтеров,
                        необходимо пройти регистрацию и получить уникальную реферальную ссылку</h2>
                    <a class="button titer__button" href="#0" data-modal=".modal--reg">Стать волонтером</a>
                </div>
            </section>
        </main>
    </div>
    <!-- modal--reg-->
    <div class="modal modal--reg">
        <div class="modal__bg"></div>
        <div class="modal__inner">
            <div class="modal__content cntWrp">
                <h2 class="modal__title">Стать волонтером</h2>
                <div class="modal__body">Здравствуйте. Здравствуйте. Оформив ежемесячное пожертвование вы помогаете активистам «SaveШиес!» в борьбе против незаконного строительства мусорного полигона.</div>
                <div class="modal__form">
                    <!-- form--reg-->
                    <form class="form form--reg" method="post" enctype="multipart/form-data" action="{{ url('register-volunteer') }}">
                        @csrf
                        <div class="form__item form__item--photo">
                            <div class="form__imgWrp">
                                <img class="form__image" src="/files/photo-placeholder.svg" />
                            </div>
                            <label class="form__label">
                                <span class="form__labelTxt">Ваше фото*</span>
{{--                                <span class="form__downloadBtn form__downloadBtn--vk" disabled>Загрузить с вк</span>--}}
                                <span class="form__downloadBtn form__downloadBtn--comp">Загрузить с компьютера</span>
                                <input type="file" hidden name="photo">
                            </label>
                        </div>
                        <div class="form__row form__row--amount">
                            <label class="form__item"><span class="form__label">Ваш имейл</span>
                                <input class="form__field" type="email" name="email" required placeholder="Введите имейл" />
                            </label>
                            <fieldset class="form__item">
                                <div class="form__label">Ваш телефон</div>
                                <input class="form__field" type="tel" name="phone" required placeholder="Введите телефон" />
                            </fieldset>
                        </div>
                        <div class="form__row">
                            <div class="form__label">Полное имя</div>
                            <div class="form__item">
                                <input class="form__field" type="text" name="name" required placeholder="Имя" />
                            </div>
                            <div class="form__item">
                                <input class="form__field" type="text" name="surname" required placeholder="Фамилия" />
                            </div>
                        </div>
                        <div class="form__row">
                            <label class="form__item"><span class="form__label">Телеграм*</span>
                                <input class="form__field" type="text" name="tg" required placeholder="Имя пользователя" />
                            </label>
                            <fieldset class="form__item">
                                <div class="form__label">Вконтакте</div>
                                <input class="form__field" type="text" name="vk" placeholder="Вставьте ссылку" />
                            </fieldset>
                        </div>
                        <div class="form__row">
                            <label class="form__item"><span class="form__label">Инстаграм</span>
                                <input class="form__field" type="text" name="inst" placeholder="Имя пользователя" />
                            </label>
                            <fieldset class="form__item">
                                <div class="form__label">Фейсбук</div>
                                <input class="form__field" type="text" name="fb" placeholder="Вставьте ссылку" />
                            </fieldset>
                        </div>
                        <label class="form__item form__item--checkbox">
                            <input type="checkbox" name="offer-agree" required><span class="form__label">Соглашаюсь с <a href="#0" target="_blank">офертой</a></span>
                        </label>
                        <label class="form__item form__item--checkbox">
                            <input type="checkbox" name="offer-agree" required><span class="form__label">Соглашаюсь на <a href="#0" target="_blank">обработку персональных данных</a></span>
                        </label>
                        <div class="form__actions">
                            <button class="button form__button" type="submit">Стать волонтером</button>
                            <div class="form__footerTxt">* — Обязательные поля</div>
                        </div>
                    </form>
                </div>
                <button class="modal__close">×</button>
            </div>
        </div>
    </div>
@endsection